name: Django CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            REPOS_TOKEN: ${{ secrets.REPOS_TOKEN }}
            EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
            EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                  python-version-file: "backend/pyproject.toml"
                  enable-cache: true

            - name: Install dependencies
              run: |
                  uv sync --dev

            - name: Run migrations
              run: python backend/manage.py migrate

            - name: Run tests
              run: python backend/manage.py test
