name: Django CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            REPOS_TOKEN: ${{ secrets.REPOS_TOKEN }}
            EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
            EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r backend/requirements.txt

            - name: Run migrations
              run: python backend/manage.py migrate

            - name: Run tests
              run: python backend/manage.py test
